- netbox_docker_plugin/__init__.py
- netbox_docker_plugin/models/container.py
- pyproject.toml
> 🏷️  Add `none` container operation

- netbox_docker_plugin/__init__.py
- netbox_docker_plugin/models/container.py
- pyproject.toml
add none into the operation command
> Add none operation

- netbox_docker_plugin/migrations/0015_remove_mount_netbox_docker_plugin_mount_unique_volume_and_more.py
- netbox_docker_plugin/models/container.py
- netbox_docker_plugin/tests/container/test_container_api.py
> 🐛 Fix volume cannot be mounted several time

- netbox_docker_plugin/__init__.py
- netbox_docker_plugin/migrations/0016_alter_env_value.py
- netbox_docker_plugin/models/container.py
- netbox_docker_plugin/tests/container/test_container_api.py
- pyproject.toml
> 🐛 Fix env variable cannot be empty string

- netbox_docker_plugin/__init__.py
- netbox_docker_plugin/forms/image.py
- netbox_docker_plugin/tests/image/test_image_views.py
- pyproject.toml
> 🩹 Made ImageID and image size read only on UI

- netbox_docker_plugin/__init__.py
- netbox_docker_plugin/api/serializers.py
- netbox_docker_plugin/forms/network.py
- netbox_docker_plugin/migrations/0017_network_state.py
- netbox_docker_plugin/models/network.py
- netbox_docker_plugin/tables.py
- netbox_docker_plugin/templates/netbox_docker_plugin/network.html
- netbox_docker_plugin/tests/network/test_network_api.py
- pyproject.toml
> 🗃️ Add Network state property

- netbox_docker_plugin/api/serializers.py
- netbox_docker_plugin/api/views.py
- netbox_docker_plugin/filtersets.py
- netbox_docker_plugin/forms/mount.py
- netbox_docker_plugin/forms/network_setting.py
- netbox_docker_plugin/migrations/0018_alter_mount_volume_alter_networksetting_network.py
- netbox_docker_plugin/models/container.py
- netbox_docker_plugin/tables.py
- netbox_docker_plugin/templates/netbox_docker_plugin/image.html
- netbox_docker_plugin/templates/netbox_docker_plugin/network.html
- netbox_docker_plugin/templates/netbox_docker_plugin/volume.html
- netbox_docker_plugin/views/image.py
- netbox_docker_plugin/views/mount.py
- netbox_docker_plugin/views/network.py
- netbox_docker_plugin/views/network_setting.py
- netbox_docker_plugin/views/volume.py
> ✨ Add used by count for volume, image and network

- netbox_docker_plugin/tables.py
- netbox_docker_plugin/templates/netbox_docker_plugin/host.html
- netbox_docker_plugin/templatetags/host.py
- netbox_docker_plugin/tests/host/test_replace_password.py
> 🐛 Replace endpoint password by *** when it's printed

- netbox_docker_plugin/api/serializers.py
- netbox_docker_plugin/filtersets.py
- netbox_docker_plugin/forms/host.py
- netbox_docker_plugin/migrations/0019_host_agent_version_host_docker_api_version.py
- netbox_docker_plugin/models/host.py
- netbox_docker_plugin/tables.py
- netbox_docker_plugin/templates/netbox_docker_plugin/host.html
- netbox_docker_plugin/tests/host/test_host_api.py
> ✨ Add Agent and Docker API version to Host entity

- netbox_docker_plugin/__init__.py
- netbox_docker_plugin/api/serializers.py
- netbox_docker_plugin/filtersets.py
- netbox_docker_plugin/forms/container.py
- netbox_docker_plugin/migrations/0020_container_hostname.py
- netbox_docker_plugin/models/container.py
- netbox_docker_plugin/tables.py
- netbox_docker_plugin/templates/netbox_docker_plugin/container.html
- netbox_docker_plugin/tests/container/test_container_api.py
- netbox_docker_plugin/tests/container/test_container_views.py
- pyproject.toml
> ✨ Add Container hostname property

- netbox_docker_plugin/__init__.py
- netbox_docker_plugin/api/serializers.py
- netbox_docker_plugin/api/urls.py
- netbox_docker_plugin/api/views.py
- netbox_docker_plugin/filtersets.py
- netbox_docker_plugin/forms/image.py
- netbox_docker_plugin/forms/registry.py
- netbox_docker_plugin/migrations/0021_registry_and_more.py
- netbox_docker_plugin/models/__init__.py
- netbox_docker_plugin/models/image.py
- netbox_docker_plugin/models/registry.py
- netbox_docker_plugin/navigation.py
- netbox_docker_plugin/tables.py
- netbox_docker_plugin/templates/netbox_docker_plugin/image.html
- netbox_docker_plugin/templates/netbox_docker_plugin/registry.html
- netbox_docker_plugin/tests/image/test_image_api.py
- netbox_docker_plugin/tests/image/test_image_views.py
- netbox_docker_plugin/tests/registry/test_registry_api.py
- netbox_docker_plugin/tests/registry/test_registry_views.py
- netbox_docker_plugin/tests/test_init.py
- netbox_docker_plugin/urls.py
- netbox_docker_plugin/views/registry.py
- pyproject.toml
> ✨ Add new Registry model

- netbox_docker_plugin/__init__.py
- netbox_docker_plugin/api/serializers.py
- pyproject.toml
> 🐛 Fix registry cannot be added on the Image creation

- netbox_docker_plugin/__init__.py
- netbox_docker_plugin/api/serializers.py
- netbox_docker_plugin/api/views.py
- netbox_docker_plugin/filtersets.py
- netbox_docker_plugin/forms/image.py
- netbox_docker_plugin/forms/registry.py
- netbox_docker_plugin/migrations/0021_registry_and_more.py
- netbox_docker_plugin/migrations/0023_delete_hosts.py
- netbox_docker_plugin/migrations/0024_registry_host_alter_registry_name_and_more.py
- netbox_docker_plugin/models/image.py
- netbox_docker_plugin/models/registry.py
- netbox_docker_plugin/templates/netbox_docker_plugin/host.html
- netbox_docker_plugin/templates/netbox_docker_plugin/registry.html
- netbox_docker_plugin/tests/container/test_container_api.py
- netbox_docker_plugin/tests/container/test_container_operation_view.py
- netbox_docker_plugin/tests/container/test_container_validation.py
- netbox_docker_plugin/tests/container/test_container_views.py
- netbox_docker_plugin/tests/host/test_host_api.py
- netbox_docker_plugin/tests/registry/test_registry_api.py
- netbox_docker_plugin/tests/registry/test_registry_views.py
- netbox_docker_plugin/views/host.py
- pyproject.toml
> :boom: Registry depends on Host

- netbox_docker_plugin/__init__.py
- netbox_docker_plugin/migrations/0025_alter_image_version.py
- netbox_docker_plugin/models/image.py
- netbox_docker_plugin/tests/image/test_image_api.py
- pyproject.toml
> :card_file_box: Upgrade the length of Image version to 256 char

- netbox_docker_plugin/api/serializers.py
- netbox_docker_plugin/migrations/0026_image_digest.py
- netbox_docker_plugin/models/image.py
- netbox_docker_plugin/templates/netbox_docker_plugin/image.html
- netbox_docker_plugin/tests/image/test_image_api.py
> :card_file_box: Add image Digest property

- netbox_docker_plugin/__init__.py
- netbox_docker_plugin/api/serializers.py
- netbox_docker_plugin/filtersets.py
- netbox_docker_plugin/forms/container.py
- netbox_docker_plugin/migrations/0027_container_restart_policy.py
- netbox_docker_plugin/models/container.py
- netbox_docker_plugin/tables.py
- netbox_docker_plugin/templates/netbox_docker_plugin/container.html
- netbox_docker_plugin/tests/container/test_container_api.py
- netbox_docker_plugin/tests/container/test_container_views.py
- pyproject.toml
> :card_file_box: Add container restart policy

- netbox_docker_plugin/__init__.py
- netbox_docker_plugin/api/serializers.py
- netbox_docker_plugin/tests/volume/test_volume_api.py
- pyproject.toml
> :bug: Anonymous Volume breaks webhook update

- netbox_docker_plugin/api/serializers.py
- netbox_docker_plugin/tests/container/test_container_api.py
> :bug: Add container display name

- .github/workflows/main_ci.yml
- .github/workflows/pr_ci.yml
- netbox_docker_plugin/__init__.py
- netbox_docker_plugin/forms/container.py
- netbox_docker_plugin/signals.py
- netbox_docker_plugin/tests/container/test_container_api.py
- netbox_docker_plugin/urls.py
- netbox_docker_plugin/views/container.py
- pyproject.toml
> :children_crossing: Prevent container's host to be changed

- netbox_docker_plugin/__init__.py
- netbox_docker_plugin/api/renderers.py
- netbox_docker_plugin/api/views.py
- netbox_docker_plugin/tests/container/test_container_api.py
- pyproject.toml
See #136 for more information.
> :lock: Escape logs (porting #136 to v2)

- netbox_docker_plugin/__init__.py
- netbox_docker_plugin/api/serializers.py
- netbox_docker_plugin/api/views.py
- netbox_docker_plugin/filtersets.py
- netbox_docker_plugin/forms/device.py
- netbox_docker_plugin/migrations/0032_device_and_more.py
- netbox_docker_plugin/models/container.py
- netbox_docker_plugin/tables.py
- netbox_docker_plugin/templates/netbox_docker_plugin/container.html
- netbox_docker_plugin/tests/container/test_container_api.py
- netbox_docker_plugin/urls.py
- netbox_docker_plugin/views/container.py
- netbox_docker_plugin/views/device.py
- pyproject.toml
> :sparkles: Add Container Device access

- netbox_docker_plugin/__init__.py
- netbox_docker_plugin/models/container.py
- netbox_docker_plugin/signals.py
- netbox_docker_plugin/templates/netbox_docker_plugin/container-layout.html
- netbox_docker_plugin/tests/container/test_container_actions.py
- pyproject.toml
> :sparkles: Add Kill operation

- netbox_docker_plugin/__init__.py
- netbox_docker_plugin/models/container.py
- netbox_docker_plugin/signals.py
- netbox_docker_plugin/templates/netbox_docker_plugin/container-layout.html
- netbox_docker_plugin/tests/container/test_container_actions.py
- pyproject.toml
> :sparkles: Add Kill operation v4

- .github/workflows/main_ci.yml
- .github/workflows/pr_ci.yml
- netbox_docker_plugin/__init__.py
- netbox_docker_plugin/api/serializers.py
- netbox_docker_plugin/forms/host.py
- netbox_docker_plugin/migrations/0033_host_operation.py
- netbox_docker_plugin/models/container.py
- netbox_docker_plugin/models/host.py
- netbox_docker_plugin/templates/netbox_docker_plugin/host.html
- netbox_docker_plugin/tests/container/test_container_actions.py
- netbox_docker_plugin/tests/host/test_host_api.py
- netbox_docker_plugin/urls.py
- netbox_docker_plugin/utilities/__init__.py
- netbox_docker_plugin/views/host.py
- pyproject.toml
> :sparkles: Add refresh host operation

- netbox_docker_plugin/__init__.py
- netbox_docker_plugin/api/serializers.py
- netbox_docker_plugin/forms/host.py
- netbox_docker_plugin/migrations/0032_host_operation.py
- netbox_docker_plugin/models/container.py
- netbox_docker_plugin/models/host.py
- netbox_docker_plugin/templates/netbox_docker_plugin/host.html
- netbox_docker_plugin/tests/container/test_container_actions.py
- netbox_docker_plugin/tests/host/test_host_api.py
- netbox_docker_plugin/urls.py
- netbox_docker_plugin/utilities/__init__.py
- netbox_docker_plugin/views/host.py
- pyproject.toml
> :sparkles: Add host refresh operation

- .github/workflows/pr_ci.yml
- netbox_docker_plugin/__init__.py
- netbox_docker_plugin/api/serializers.py
- netbox_docker_plugin/filtersets.py
- netbox_docker_plugin/forms/container.py
- netbox_docker_plugin/forms/log_driver_option.py
- netbox_docker_plugin/migrations/0035_container_log_driver_logdriveroption.py
- netbox_docker_plugin/models/container.py
- netbox_docker_plugin/tables.py
- netbox_docker_plugin/templates/netbox_docker_plugin/container.html
- netbox_docker_plugin/tests/container/test_container_api.py
- netbox_docker_plugin/tests/container/test_container_views.py
- netbox_docker_plugin/urls.py
- netbox_docker_plugin/views/log_driver_option.py
- pyproject.toml
Add Log driver for container. Related to https://github.com/SaaShup/netbox-docker-agent/issues/128
> :sparkles: Add Log driver for container

- netbox_docker_plugin/__init__.py
- netbox_docker_plugin/migrations/1039_alter_port_public_port.py
- netbox_docker_plugin/models/container.py
- netbox_docker_plugin/tests/container/test_container_api.py
- pyproject.toml
Part of the project to deactivate a container public port.
> :card_file_box: Made possible to set public port to -1
